spring:
  application:
    name: neverpile eureka (tutorial 04)
  boot.admin.client:
    url: [http://localhost:1001]
    username: admin
    password: admin

management:
  health:
    cassandra.enabled: false
    db.enabled: false
    elasticsearch.enabled: false
  endpoints:
    web.exposure:
      include: '*'
  endpoint:
    health.show-details: always

neverpile:
  url-crypto:
    shared-secret:
      enabled: true
      secret-key: ps634xpe85en4a779g98

neverpile-eureka:
  data-path: data

  bridge:
    storage:
      filesystem:
        rootPath: ${neverpile-eureka.data-path}/objects

  wal:
    directory: ${neverpile-eureka.data-path}/wal
