spring:
  application:
    name: neverpile eureka (tutorial 03)
  boot.admin.client:
    url: [http://localhost:5001]
    username: admin
    password: admin
  main:
    allow-circular-references: true

management:
  health:
    cassandra.enabled: false
    db.enabled: false
    elasticsearch.enabled: false
  endpoints:
    web.exposure:
      include: '*'
  endpoint:
    health.show-details: always

neverpile-eureka:
  data-path: data

  bridge:
    storage:
      filesystem:
        rootPath: ${neverpile-eureka.data-path}/objects

  wal:
    directory: ${neverpile-eureka.data-path}/wal
