spring:
  application:
    name: neverpile eureka (tutorial 03)
  boot.admin.client:
    url: [http://localhost:1001]
    username: admin
    password: admin

management:
  health:
    cassandra.enabled: false
    db.enabled: false
    elasticsearch.enabled: false
  endpoints:
    web.exposure:
      include: '*'
  endpoint:
    health.show-details: always

neverpile-eureka:
  data-path: data

  bridge:
    storage:
      filesystem:
        rootPath: ${neverpile-eureka.data-path}/objects

  wal:
    directory: ${neverpile-eureka.data-path}/wal

  oauth2:
    embedded-authorization-server:
      enabled: true
      key: "Signing§Key"
